### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by cmsirbu** [cmsirbu/inog#1]
Add code of conduct under another section - possibly Charter?

Draft:
"b) Code of Conduct: Our group is dedicated to providing a 
harassment-free event experience for everyone, regardless of gender, 
gender identity and expression, age, sexual orientation, disability, 
physical appearance, body size, race, ethnicity, or religion (or lack 
thereof). We do not tolerate harassment of group participants in any 
form. Sexual language and imagery is not appropriate for any meetup 
venue, including talks, workshops, parties, Twitter and other online 
media. Group participants violating these rules may be sanctioned or 
expelled from the group (without a refund if applicable) at the 
discretion of the group organisers. Ref: http://confcodeofconduct.com/ "

My suggestion is in addition to that have one big rule (inspired from the Rock Paper Shotgun gaming community): "Be excellent to each other."

**Comment by donalod** [comment]
Can totally add under Charter (but at the top please)... we need a broad array of people coming and knowing what we stand for!

Many have found that this is not enough and does not give confidence to the less shy and vulnerable amongst us. The above Code of Conduct is short form and consider Best Current Practice for any meetup or conference. Why? http://www.ashedryden.com/blog/codes-of-conduct-101-faq

Diversity, Awareness, and Welcoming Spaces: http://freelancing-gods.com/2015/03/01/diversity-awareness-and-welcoming-spaces.html
Great conferences mention both: http://www.webdirections.org/web-directions-event-code-of-conduct/ 

Here is my personal reasoning (after having organised events and meetups since 2008): http://bsdosx.blogspot.ie/2013/10/codified.html

It is not enough as a white male to say "Be excellent to each other" I'm sad to say. If we want a diverse and healthy community, one that by its very nature already ostracizes many by virtue of being white males, then sending strong EXPLICIT signals about how we expect each other to act is in fact crucial.

**Comment by cmsirbu** [comment]
I agree... maybe I was not too clear... I was saying that "be excellent to each other" should be the one-liner version.  Even RPS explain what they mean by "excellent": http://www.rockpapershotgun.com/forums/showthread.php?21413-The-New-Forum-Rules in a less formal way, for reasons which should be obvious.

I suggest we put in the "less-quick version" once our events grow in size, as half of it would need heavy modification in order to be relevant for now.
